# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e470b97262c216e64f6384e70142c9baa3810cedb1d05768314bea8291e79d1a4305d20fc382e54460e2a1f200d0921edef98d66254b839c61d207f22922b04
  facebook_app_id: 1477138175909836
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: cf01d17804845ce1b0da79e3fcfd37c487343e15a9daaf7b53ad1a00cd2f722539f67c2cb45dbabae6b2afaa4f345437e0fa3312d8de1a0e498814a80cefd690
  facebook_app_id: 1477138175909836
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 1477138175909836
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
